{
 "title": "Search Engine metrics Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": { "query": "label_values(namespace)" } },
   { "name": "percentile", "label": "Percentile", "query": "0.95" },
   {
    "name": "rate",
    "label": "Rate interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "Rate of parsed pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(crawler_pages_parsed[5m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Parse time percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(crawler_page_parse_time_bucket[5m])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Time percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(crawler_site_connection_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of Web Pages Served per 1 hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(web_pages_served[1h])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Page generation time percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile,sum(rate(web_page_gen_time_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}